apiVersion: v1
kind: ReplicationController
metadata:
  name: vertex-rc
spec:
   replicas: 3
   selector: 
     app: myvertexapp
     version: 2.6.1
   template:                                     
     metadata:
       labels:
          app: myvertexapp
          version: 2.6.1
     spec:
        containers:
        - name: myvertexapp-container
          image: shubhamtech/myjava1:1
          ports: 
          - containerPort: 8080